import Foundation
import FoundationInterfaces
import FoundationTransactions
import OpenCombine
import Testing

@testable import SwiftRobotics

// MARK: - Test Infrastructure

/// Mock pipe for testing TransactionHandler
final class MockTransactionPipe: MessageDuplex, @unchecked Sendable {
    private let lock = NSLock()

    var sentCommands: [(command: String, priority: Int)] = []
    var stringMessageHandler: (@Sendable (String) -> Void)?
    var dataMessageHandler: (@Sendable (Data) -> Void)?

    // MARK: - MessageSendable

    @discardableResult
    func send(to id: (any Identifiable)?, _ data: Data, _ priority: Int, _ queueIfDisconnected: Bool) -> Bool {
        if let message = String(data: data, encoding: .utf8) {
            return send(to: id, message, priority, queueIfDisconnected)
        }
        return false
    }

    @discardableResult
    func send(to id: (any Identifiable)?, _ message: String, _ priority: Int, _ queueIfDisconnected: Bool) -> Bool {
        lock.lock()
        sentCommands.append((message, priority))
        lock.unlock()
        return true
    }

    // MARK: - MessageReceivable

    func setDataMessageHandler(_ handler: (@Sendable (Data) -> Void)?) {
        lock.lock()
        dataMessageHandler = handler
        lock.unlock()
    }

    func setStringMessageHandler(_ handler: (@Sendable (String) -> Void)?) {
        lock.lock()
        stringMessageHandler = handler
        lock.unlock()
    }

    func handleMessage(_ message: String) async {
        stringMessageHandler?(message)
    }

    // MARK: - Test Helpers

    /// Simulate receiving a message from the device
    func simulateInbound(_ message: String) async {
        stringMessageHandler?(message)
    }

    func reset() {
        lock.lock()
        sentCommands.removeAll()
        lock.unlock()
    }
}

/// Thread-safe message collector for use inside @Sendable closures in tests.
private final class MessageCollector: @unchecked Sendable {
    private let lock = NSLock()
    private var _messages: [String] = []

    var messages: [String] {
        lock.lock(); defer { lock.unlock() }
        return _messages
    }

    func append(_ message: String) {
        lock.lock(); defer { lock.unlock() }
        _messages.append(message)
    }
}

// MARK: - Basic Transaction Tests

@Suite("TransactionHandler Basic Tests")
struct TransactionHandlerBasicTests {

    @Test("Handler initializes with correct resource ID and state")
    func testInitialization() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)

        #expect(handler.resourceID == "test-robot")
        #expect(handler.resourceState == .idle)
        #expect(handler.hasPipe == false)
    }

    @Test("Handler attaches and detaches pipe correctly")
    func testPipeAttachment() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()

        #expect(handler.hasPipe == false)

        handler.attachPipe(pipe)
        #expect(handler.hasPipe == true)

        handler.detachPipe()
        #expect(handler.hasPipe == false)
    }

    @Test("Submit sends command through pipe")
    func testSubmitSendsCommand() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("home", commandType: .serial)
        let txn = handler.submit(cmd)

        #expect(pipe.sentCommands.count == 1)
        #expect(pipe.sentCommands[0].command.contains("\(txn.id)"))
        #expect(pipe.sentCommands[0].command.contains("home"))
    }

    @Test("Device state updates correctly")
    func testDeviceStateUpdate() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .disconnected)

        #expect(handler.resourceState == .disconnected)

        handler.updateResourceState(.idle)
        #expect(handler.resourceState == .idle)

        handler.updateResourceState(.busy)
        #expect(handler.resourceState == .busy)
    }
}

// MARK: - Transaction ID Resolution Tests

@Suite("Transaction ID Resolution Tests")
struct TransactionIDResolutionTests {

    @Test("Auto-generates transaction ID when command trID is negative")
    func testAutoGeneratedID() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("status", trID: -1, commandType: .parallel)
        let txn = handler.submit(cmd)

        #expect(txn.id >= 1)
    }

    @Test("Uses command trID when valid (>= 0)")
    func testCommandProvidedID() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("status", trID: 12345, commandType: .parallel)
        let txn = handler.submit(cmd)

        #expect(txn.id == 12345)
    }

    @Test("Sequential auto-generated IDs increment")
    func testSequentialIDs() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn1 = handler.submit(RobotCommand("status", commandType: .parallel))
        let txn2 = handler.submit(RobotCommand("status", commandType: .parallel))
        let txn3 = handler.submit(RobotCommand("status", commandType: .parallel))

        #expect(txn2.id == txn1.id + 1)
        #expect(txn3.id == txn2.id + 1)
    }
}

// MARK: - Timeout Resolution Tests

@Suite("Timeout Resolution Tests")
struct TimeoutResolutionTests {

    @Test("Uses handler default timeout when command has no timeout")
    func testDefaultTimeout() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.defaultTimeout = 45.0
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("status", timeout: nil, commandType: .parallel)
        let txn = handler.submit(cmd)

        #expect(txn.timeout == 45.0)
    }

    @Test("Uses command timeout when specified")
    func testCommandTimeout() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.defaultTimeout = 30.0
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("moveto", timeout: 60.0, commandType: .serial)
        let txn = handler.submit(cmd)

        #expect(txn.timeout == 60.0)
    }

    @Test("Explicit submit timeout overrides command timeout")
    func testExplicitTimeout() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.defaultTimeout = 30.0
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("moveto", timeout: 60.0, commandType: .serial)
        let txn = handler.submit(cmd, timeout: 120.0)

        #expect(txn.timeout == 120.0)
    }
}

// MARK: - Command Category Tests

@Suite("Command Category Tests")
struct CommandCategoryTests {

    @Test("Serial commands execute one at a time")
    func testSerialQueue() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let motion1 = handler.submit(RobotCommand("home", commandType: .serial))
        let motion2 = handler.submit(RobotCommand("moveto", commandType: .serial))

        #expect(motion1.state == .awaitingAck)
        #expect(motion2.state == .queued)
        #expect(handler.serialQueueCount == 1)
        #expect(handler.isSerialBusy == true)
    }

    @Test("Parallel commands execute concurrently")
    func testParallelConcurrent() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let query1 = handler.submit(RobotCommand("status", commandType: .parallel))
        let query2 = handler.submit(RobotCommand("currentpose", commandType: .parallel))
        let query3 = handler.submit(RobotCommand("ver", commandType: .parallel))

        #expect(query1.state == .awaitingAck)
        #expect(query2.state == .awaitingAck)
        #expect(query3.state == .awaitingAck)
        #expect(handler.activeParallelCount == 3)
    }

    @Test("Exclusive commands execute one at a time")
    func testExclusiveSerial() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let set1 = handler.submit(RobotCommand("setPoint", commandType: .exclusive))
        let set2 = handler.submit(RobotCommand("calibrate", commandType: .exclusive))

        #expect(set1.state == .awaitingAck)
        #expect(set2.state == .queued)
    }

    @Test("Serial queue processes next after completion")
    func testSerialQueueProcessing() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let motion1 = handler.submit(RobotCommand("home", commandType: .serial))
        let motion2 = handler.submit(RobotCommand("moveto", commandType: .serial))

        #expect(handler.serialQueueCount == 1)

        handler.processAcknowledgment(transactionID: motion1.id)
        handler.processResponse(transactionID: motion1.id, response: "OK")

        #expect(motion1.state == .completed)
        #expect(motion2.state == .awaitingAck)
        #expect(handler.serialQueueCount == 0)
    }
}

// MARK: - Transaction Lifecycle Tests

@Suite("Transaction Lifecycle Tests")
struct TransactionLifecycleTests {

    @Test("Transaction progresses through states correctly")
    func testStateProgression() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .parallel))
        #expect(txn.state == .awaitingAck)

        handler.processAcknowledgment(transactionID: txn.id)
        #expect(txn.state == .executing)

        handler.processResponse(transactionID: txn.id, response: "OK")
        #expect(txn.state == .completed)
        #expect(txn.isTerminal == true)
    }

    @Test("Transaction captures response")
    func testResponseCapture() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .parallel))
        handler.processAcknowledgment(transactionID: txn.id)
        handler.processResponse(transactionID: txn.id, response: "RUNNING")

        #expect(txn.response == "RUNNING")
    }

    @Test("Transaction handles error correctly")
    func testErrorHandling() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("moveto", commandType: .serial))
        handler.processAcknowledgment(transactionID: txn.id)
        handler.processError(transactionID: txn.id, message: "Joint limit exceeded")

        #expect(txn.state == .failed)
        #expect(txn.isTerminal == true)
        if case .resourceError(let msg) = txn.error {
            #expect(msg == "Joint limit exceeded")
        } else {
            Issue.record("Expected resourceError")
        }
    }

    @Test("Transaction can be cancelled")
    func testCancellation() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("moveto", commandType: .serial))
        handler.cancel(transactionID: txn.id)

        #expect(txn.state == .cancelled)
        #expect(txn.isTerminal == true)
    }
}

// MARK: - Resource State Tests

@Suite("Resource State Tests")
struct ResourceStateTests {

    @Test("Commands fail when resource is disconnected")
    func testDisconnectedState() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .disconnected)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .serial))

        #expect(txn.state == .failed)
        if case .resourceNotReady(let state) = txn.error {
            #expect(state == .disconnected)
        } else {
            Issue.record("Expected resourceNotReady error")
        }
    }

    @Test("Commands fail when resource is in error state")
    func testErrorState() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .error)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .serial))

        #expect(txn.state == .failed)
    }

    @Test("Commands fail when resource is in estop")
    func testEstopState() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .estop)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .serial))

        #expect(txn.state == .failed)
    }

    @Test("Resource state change to error cancels active transactions")
    func testStateChangeCancel() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .serial))
        #expect(txn.state == .awaitingAck)

        handler.updateResourceState(.error)

        #expect(txn.state == .failed)
    }

    @Test("Serial command sets resource to busy on ack")
    func testBusyStateOnSerial() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .serial))
        #expect(handler.resourceState == .idle)

        handler.processAcknowledgment(transactionID: txn.id)
        #expect(handler.resourceState == .busy)
    }
}

// MARK: - Event Handling Tests

@Suite("Event Handling Tests")
struct EventHandlingTests {

    @Test("Solicited events route to transaction")
    func testSolicitedEvents() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("moveto", commandType: .serial))
        handler.processAcknowledgment(transactionID: txn.id)

        handler.processEvent(code: 1001, payload: "waypoint-1", transactionID: txn.id)
        handler.processEvent(code: 1002, payload: "50%", transactionID: txn.id)

        #expect(txn.events.count == 2)
        #expect(txn.events[0].code == 1001)
        #expect(txn.events[0].payload == "waypoint-1")
        #expect(txn.events[1].code == 1002)
    }

    @Test("Unsolicited events emit on handler publisher")
    func testUnsolicitedEvents() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var receivedEvents: [TransactionEvent] = []
        var cancellables = Set<AnyCancellable>()

        handler.unsolicitedEventPublisher
            .sink { event in
                receivedEvents.append(event)
            }
            .store(in: &cancellables)

        handler.processEvent(code: 2001, payload: "collision detected", transactionID: nil)
        handler.processEvent(code: 2002, payload: "safety zone breach", transactionID: nil)

        #expect(receivedEvents.count == 2)
        #expect(receivedEvents[0].code == 2001)
        #expect(receivedEvents[0].isUnsolicited == true)
    }

    @Test("Event with unknown transaction ID treated as unsolicited")
    func testUnknownTransactionEvent() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var receivedEvents: [TransactionEvent] = []
        var cancellables = Set<AnyCancellable>()

        handler.unsolicitedEventPublisher
            .sink { event in
                receivedEvents.append(event)
            }
            .store(in: &cancellables)

        handler.processEvent(code: 9999, payload: "unknown", transactionID: 99999)

        #expect(receivedEvents.count == 1)
    }
}

// MARK: - Bidirectionality Tests

@Suite("Bidirectionality Tests")
struct BidirectionalityTests {

    @Test("inboundTransactionHandler is called for unknown transaction IDs")
    func testInboundHandlerRouting() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let collector = MessageCollector()

        handler.messageParser = { h, message in
            // Simulate a simple parser that routes unknown tx_ids to inbound handler
            if message.hasPrefix("<999,") {
                h.inboundTransactionHandler?(h, message)
            }
        }

        handler.inboundTransactionHandler = { _, message in
            collector.append(message)
        }

        await pipe.simulateInbound("<999,cmd,home,>")
        await pipe.simulateInbound("<999,cmd,status,>")

        #expect(collector.messages.count == 2)
        #expect(collector.messages[0] == "<999,cmd,home,>")
    }

    @Test("inboundTransactionHandler nil does not crash")
    func testInboundHandlerNilSafe() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        handler.messageParser = { h, message in
            h.inboundTransactionHandler?(h, message)
        }

        // No inboundTransactionHandler set — should not crash
        await pipe.simulateInbound("<42,cmd,home,>")
    }
}

// MARK: - Message Parser Tests

@Suite("Message Parser Tests")
struct MessageParserTests {

    @Test("Message parser receives inbound messages")
    func testMessageParserRouting() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let collector = MessageCollector()
        handler.messageParser = { _, message in
            collector.append(message)
        }

        await pipe.simulateInbound("<1,ACK>")
        await pipe.simulateInbound("<1,OK,done>")

        #expect(collector.messages.count == 2)
        #expect(collector.messages[0] == "<1,ACK>")
        #expect(collector.messages[1] == "<1,OK,done>")
    }
}

// MARK: - Stress Tests

@Suite("TransactionHandler Stress Tests")
struct TransactionHandlerStressTests {

    @Test("Handles many concurrent parallel transactions")
    func testManyParallel() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.maxConcurrentParallel = 100
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var transactions: [Transaction<RobotCommand>] = []

        for i in 0..<50 {
            let txn = handler.submit(RobotCommand("status\(i)", commandType: .parallel))
            transactions.append(txn)
        }

        #expect(handler.activeParallelCount == 50)
        #expect(transactions.allSatisfy { $0.state == .awaitingAck })

        for txn in transactions {
            handler.processAcknowledgment(transactionID: txn.id)
            handler.processResponse(transactionID: txn.id, response: "OK")
        }

        #expect(handler.activeParallelCount == 0)
        #expect(transactions.allSatisfy { $0.state == .completed })
    }

    @Test("Handles deep serial queue")
    func testDeepSerialQueue() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.maxSerialQueueDepth = 50
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var transactions: [Transaction<RobotCommand>] = []

        for i in 0..<25 {
            let txn = handler.submit(RobotCommand("move\(i)", commandType: .serial))
            transactions.append(txn)
        }

        #expect(transactions[0].state == .awaitingAck)
        #expect(handler.serialQueueCount == 24)

        for txn in transactions {
            handler.processAcknowledgment(transactionID: txn.id)
            handler.processResponse(transactionID: txn.id, response: "OK")
        }

        #expect(handler.serialQueueCount == 0)
        #expect(transactions.allSatisfy { $0.state == .completed })
    }

    @Test("Rapid submit and complete cycle")
    func testRapidCycle() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        for i in 0..<100 {
            let txn = handler.submit(RobotCommand("query\(i)", commandType: .parallel))
            handler.processAcknowledgment(transactionID: txn.id)
            handler.processResponse(transactionID: txn.id, response: "OK\(i)")

            #expect(txn.state == .completed)
            #expect(txn.response == "OK\(i)")
        }

        #expect(pipe.sentCommands.count == 100)
    }

    @Test("Mixed category concurrent operations")
    func testMixedCategories() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let serial1 = handler.submit(RobotCommand("home", commandType: .serial))
        let parallel1 = handler.submit(RobotCommand("status", commandType: .parallel))
        let parallel2 = handler.submit(RobotCommand("pose", commandType: .parallel))
        let exclusive1 = handler.submit(RobotCommand("setPoint", commandType: .exclusive))
        let serial2 = handler.submit(RobotCommand("moveto", commandType: .serial))

        #expect(serial1.state == .awaitingAck)
        #expect(serial2.state == .queued)
        #expect(parallel1.state == .awaitingAck)
        #expect(parallel2.state == .awaitingAck)
        #expect(exclusive1.state == .awaitingAck)

        handler.processAcknowledgment(transactionID: serial1.id)
        handler.processResponse(transactionID: serial1.id)

        #expect(serial1.state == .completed)
        #expect(serial2.state == .awaitingAck)
    }

    @Test("Cancel all clears everything")
    func testCancelAll() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let motion1 = handler.submit(RobotCommand("home", commandType: .serial))
        let motion2 = handler.submit(RobotCommand("moveto", commandType: .serial))
        let query1 = handler.submit(RobotCommand("status", commandType: .parallel))
        let settable1 = handler.submit(RobotCommand("setPoint", commandType: .exclusive))

        handler.cancelAll()

        #expect(motion1.state == .failed)
        #expect(motion2.state == .failed)
        #expect(query1.state == .failed)
        #expect(settable1.state == .failed)
        #expect(handler.serialQueueCount == 0)
        #expect(handler.activeParallelCount == 0)
    }
}

// MARK: - Publisher Tests

@Suite("TransactionHandler Publisher Tests")
struct PublisherTests {

    @Test("Resource state publisher emits changes")
    func testResourceStatePublisher() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .disconnected)

        var receivedStates: [ResourceState] = []
        var cancellables = Set<AnyCancellable>()

        handler.resourceStatePublisher
            .sink { state in
                receivedStates.append(state)
            }
            .store(in: &cancellables)

        handler.updateResourceState(.idle)
        handler.updateResourceState(.busy)
        handler.updateResourceState(.idle)

        #expect(receivedStates.contains(.idle))
        #expect(receivedStates.contains(.busy))
    }

    @Test("Transaction state publisher emits changes")
    func testTransactionStatePublisher() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .parallel))

        var receivedStates: [TransactionState] = []
        var cancellables = Set<AnyCancellable>()

        txn.statePublisher
            .sink { state in
                receivedStates.append(state)
            }
            .store(in: &cancellables)

        handler.processAcknowledgment(transactionID: txn.id)
        handler.processResponse(transactionID: txn.id)

        #expect(receivedStates.contains(.executing))
        #expect(receivedStates.contains(.completed))
    }

    @Test("Transaction result publisher emits results")
    func testTransactionResultPublisher() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .parallel))

        var receivedResults: [TransactionResult] = []
        var cancellables = Set<AnyCancellable>()

        txn.resultPublisher
            .sink { result in
                receivedResults.append(result)
            }
            .store(in: &cancellables)

        handler.processAcknowledgment(transactionID: txn.id)
        handler.processResponse(transactionID: txn.id, response: "RUNNING")

        #expect(receivedResults.count >= 2)

        let hasAck = receivedResults.contains { result in
            if case .acknowledged = result { return true }
            return false
        }
        #expect(hasAck)

        let hasCompleted = receivedResults.contains { result in
            if case .completed(_, let response) = result {
                return response == "RUNNING"
            }
            return false
        }
        #expect(hasCompleted)
    }
}
