import Testing
import Foundation
import OpenCombine

@testable import SwiftRobotics

// MARK: - Test Infrastructure

/// Mock pipe for testing TransactionHandler
final class MockTransactionPipe: TransactionPipe, @unchecked Sendable {
    private let lock = NSLock()

    var sentCommands: [(command: String, transactionID: Int)] = []
    var inboundHandler: (@Sendable (String) async -> Void)?

    @discardableResult
    func sendCommand(_ command: String, transactionID: Int) -> Bool {
        lock.lock()
        sentCommands.append((command, transactionID))
        lock.unlock()
        return true
    }

    func setInboundHandler(_ handler: (@Sendable (String) async -> Void)?) {
        lock.lock()
        inboundHandler = handler
        lock.unlock()
    }

    /// Simulate receiving a message from the device
    func simulateInbound(_ message: String) async {
        await inboundHandler?(message)
    }

    func reset() {
        lock.lock()
        sentCommands.removeAll()
        lock.unlock()
    }
}

// MARK: - Basic Transaction Tests

@Suite("TransactionHandler Basic Tests")
struct TransactionHandlerBasicTests {

    @Test("Handler initializes with correct resource ID and state")
    func testInitialization() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)

        #expect(handler.resourceID == "test-robot")
        #expect(handler.deviceState == .idle)
        #expect(handler.hasPipe == false)
    }

    @Test("Handler attaches and detaches pipe correctly")
    func testPipeAttachment() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()

        #expect(handler.hasPipe == false)

        handler.attachPipe(pipe)
        #expect(handler.hasPipe == true)

        handler.detachPipe()
        #expect(handler.hasPipe == false)
    }

    @Test("Submit sends command through pipe")
    func testSubmitSendsCommand() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("home", commandType: .motion)
        let txn = handler.submit(cmd)

        #expect(pipe.sentCommands.count == 1)
        #expect(pipe.sentCommands[0].transactionID == txn.id)
        #expect(pipe.sentCommands[0].command.contains("home"))
    }

    @Test("Device state updates correctly")
    func testDeviceStateUpdate() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .disconnected)

        #expect(handler.deviceState == .disconnected)

        handler.updateDeviceState(.idle)
        #expect(handler.deviceState == .idle)

        handler.updateDeviceState(.busy)
        #expect(handler.deviceState == .busy)
    }
}

// MARK: - Transaction ID Resolution Tests

@Suite("Transaction ID Resolution Tests")
struct TransactionIDResolutionTests {

    @Test("Auto-generates transaction ID when command trID is negative")
    func testAutoGeneratedID() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("status", trID: -1, commandType: .query)
        let txn = handler.submit(cmd)

        #expect(txn.id >= 1)
    }

    @Test("Uses command trID when valid (>= 0)")
    func testCommandProvidedID() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("status", trID: 12345, commandType: .query)
        let txn = handler.submit(cmd)

        #expect(txn.id == 12345)
    }

    @Test("Sequential auto-generated IDs increment")
    func testSequentialIDs() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn1 = handler.submit(RobotCommand("status", commandType: .query))
        let txn2 = handler.submit(RobotCommand("status", commandType: .query))
        let txn3 = handler.submit(RobotCommand("status", commandType: .query))

        #expect(txn2.id == txn1.id + 1)
        #expect(txn3.id == txn2.id + 1)
    }
}

// MARK: - Timeout Resolution Tests

@Suite("Timeout Resolution Tests")
struct TimeoutResolutionTests {

    @Test("Uses handler default timeout when command has no timeout")
    func testDefaultTimeout() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.defaultTimeout = 45.0
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("status", timeout: nil, commandType: .query)
        let txn = handler.submit(cmd)

        #expect(txn.timeout == 45.0)
    }

    @Test("Uses command timeout when specified")
    func testCommandTimeout() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.defaultTimeout = 30.0
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("moveto", timeout: 60.0, commandType: .motion)
        let txn = handler.submit(cmd)

        #expect(txn.timeout == 60.0)
    }

    @Test("Explicit submit timeout overrides command timeout")
    func testExplicitTimeout() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.defaultTimeout = 30.0
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let cmd = RobotCommand("moveto", timeout: 60.0, commandType: .motion)
        let txn = handler.submit(cmd, timeout: 120.0)

        #expect(txn.timeout == 120.0)
    }
}

// MARK: - Command Category Tests

@Suite("Command Category Tests")
struct CommandCategoryTests {

    @Test("Motion commands execute serially")
    func testMotionSerial() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let motion1 = handler.submit(RobotCommand("home", commandType: .motion))
        let motion2 = handler.submit(RobotCommand("moveto", commandType: .motion))

        #expect(motion1.state == .awaitingAck)
        #expect(motion2.state == .queued)
        #expect(handler.motionQueueCount == 1)
        #expect(handler.isMotionBusy == true)
    }

    @Test("Query commands execute in parallel")
    func testQueryParallel() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let query1 = handler.submit(RobotCommand("status", commandType: .query))
        let query2 = handler.submit(RobotCommand("currentpose", commandType: .query))
        let query3 = handler.submit(RobotCommand("ver", commandType: .query))

        #expect(query1.state == .awaitingAck)
        #expect(query2.state == .awaitingAck)
        #expect(query3.state == .awaitingAck)
        #expect(handler.activeQueryCount == 3)
    }

    @Test("Settable commands execute serially")
    func testSettableSerial() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let set1 = handler.submit(RobotCommand("setPoint", commandType: .settable))
        let set2 = handler.submit(RobotCommand("calibrate", commandType: .settable))

        #expect(set1.state == .awaitingAck)
        #expect(set2.state == .queued)
    }

    @Test("Motion queue processes next after completion")
    func testMotionQueueProcessing() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let motion1 = handler.submit(RobotCommand("home", commandType: .motion))
        let motion2 = handler.submit(RobotCommand("moveto", commandType: .motion))

        #expect(handler.motionQueueCount == 1)

        // Complete the first motion
        handler.processAcknowledgment(transactionID: motion1.id)
        handler.processResponse(transactionID: motion1.id, response: "OK")

        #expect(motion1.state == .completed)
        #expect(motion2.state == .awaitingAck)
        #expect(handler.motionQueueCount == 0)
    }
}

// MARK: - Transaction Lifecycle Tests

@Suite("Transaction Lifecycle Tests")
struct TransactionLifecycleTests {

    @Test("Transaction progresses through states correctly")
    func testStateProgression() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .query))
        #expect(txn.state == .awaitingAck)

        handler.processAcknowledgment(transactionID: txn.id)
        #expect(txn.state == .executing)

        handler.processResponse(transactionID: txn.id, response: "OK")
        #expect(txn.state == .completed)
        #expect(txn.isTerminal == true)
    }

    @Test("Transaction captures response")
    func testResponseCapture() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .query))
        handler.processAcknowledgment(transactionID: txn.id)
        handler.processResponse(transactionID: txn.id, response: "RUNNING")

        #expect(txn.response == "RUNNING")
    }

    @Test("Transaction handles error correctly")
    func testErrorHandling() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("moveto", commandType: .motion))
        handler.processAcknowledgment(transactionID: txn.id)
        handler.processError(transactionID: txn.id, message: "Joint limit exceeded")

        #expect(txn.state == .failed)
        #expect(txn.isTerminal == true)
        if case .deviceError(let msg) = txn.error {
            #expect(msg == "Joint limit exceeded")
        } else {
            Issue.record("Expected deviceError")
        }
    }

    @Test("Transaction can be cancelled")
    func testCancellation() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("moveto", commandType: .motion))
        handler.cancel(transactionID: txn.id)

        #expect(txn.state == .cancelled)
        #expect(txn.isTerminal == true)
    }
}

// MARK: - Device State Tests

@Suite("Device State Tests")
struct DeviceStateTests {

    @Test("Commands fail when device is disconnected")
    func testDisconnectedState() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .disconnected)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .motion))

        #expect(txn.state == .failed)
        if case .deviceNotReady(let state) = txn.error {
            #expect(state == .disconnected)
        } else {
            Issue.record("Expected deviceNotReady error")
        }
    }

    @Test("Commands fail when device is in error state")
    func testErrorState() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .error)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .motion))

        #expect(txn.state == .failed)
    }

    @Test("Commands fail when device is in estop")
    func testEstopState() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .estop)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .motion))

        #expect(txn.state == .failed)
    }

    @Test("Device state change to error cancels active transactions")
    func testStateChangeCancel() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .motion))
        #expect(txn.state == .awaitingAck)

        handler.updateDeviceState(.error)

        #expect(txn.state == .failed)
    }

    @Test("Motion command sets device to busy on ack")
    func testBusyStateOnMotion() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("home", commandType: .motion))
        #expect(handler.deviceState == .idle)

        handler.processAcknowledgment(transactionID: txn.id)
        #expect(handler.deviceState == .busy)
    }
}

// MARK: - Event Handling Tests

@Suite("Event Handling Tests")
struct EventHandlingTests {

    @Test("Solicited events route to transaction")
    func testSolicitedEvents() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("moveto", commandType: .motion))
        handler.processAcknowledgment(transactionID: txn.id)

        // Send a solicited event
        handler.processEvent(code: 1001, payload: "waypoint-1", transactionID: txn.id)
        handler.processEvent(code: 1002, payload: "50%", transactionID: txn.id)

        #expect(txn.events.count == 2)
        #expect(txn.events[0].code == 1001)
        #expect(txn.events[0].payload == "waypoint-1")
        #expect(txn.events[1].code == 1002)
    }

    @Test("Unsolicited events emit on handler publisher")
    func testUnsolicitedEvents() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var receivedEvents: [DeviceEvent] = []
        var cancellables = Set<AnyCancellable>()

        handler.unsolicitedEventPublisher
            .sink { event in
                receivedEvents.append(event)
            }
            .store(in: &cancellables)

        // Send unsolicited events (no transaction ID)
        handler.processEvent(code: 2001, payload: "collision detected", transactionID: nil)
        handler.processEvent(code: 2002, payload: "safety zone breach", transactionID: nil)

        #expect(receivedEvents.count == 2)
        #expect(receivedEvents[0].code == 2001)
        #expect(receivedEvents[0].isUnsolicited == true)
    }

    @Test("Event with unknown transaction ID treated as unsolicited")
    func testUnknownTransactionEvent() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var receivedEvents: [DeviceEvent] = []
        var cancellables = Set<AnyCancellable>()

        handler.unsolicitedEventPublisher
            .sink { event in
                receivedEvents.append(event)
            }
            .store(in: &cancellables)

        // Event with non-existent transaction ID
        handler.processEvent(code: 9999, payload: "unknown", transactionID: 99999)

        #expect(receivedEvents.count == 1)
    }
}

// MARK: - Message Parser Tests

@Suite("Message Parser Tests")
struct MessageParserTests {

    @Test("Message parser receives inbound messages")
    func testMessageParserRouting() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var parsedMessages: [String] = []
        handler.messageParser = { _, message in
            parsedMessages.append(message)
        }

        // Simulate inbound message
        await pipe.simulateInbound("<1,ACK>")
        await pipe.simulateInbound("<1,OK,done>")

        #expect(parsedMessages.count == 2)
        #expect(parsedMessages[0] == "<1,ACK>")
        #expect(parsedMessages[1] == "<1,OK,done>")
    }
}

// MARK: - Stress Tests

@Suite("TransactionHandler Stress Tests")
struct TransactionHandlerStressTests {

    @Test("Handles many concurrent query transactions")
    func testManyQueries() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.maxConcurrentQueries = 100
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var transactions: [Transaction<RobotCommand>] = []

        for i in 0..<50 {
            let txn = handler.submit(RobotCommand("status\(i)", commandType: .query))
            transactions.append(txn)
        }

        #expect(handler.activeQueryCount == 50)
        #expect(transactions.allSatisfy { $0.state == .awaitingAck })

        // Complete all
        for txn in transactions {
            handler.processAcknowledgment(transactionID: txn.id)
            handler.processResponse(transactionID: txn.id, response: "OK")
        }

        #expect(handler.activeQueryCount == 0)
        #expect(transactions.allSatisfy { $0.state == .completed })
    }

    @Test("Handles deep motion queue")
    func testDeepMotionQueue() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        handler.maxMotionQueueDepth = 50
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        var transactions: [Transaction<RobotCommand>] = []

        for i in 0..<25 {
            let txn = handler.submit(RobotCommand("move\(i)", commandType: .motion))
            transactions.append(txn)
        }

        #expect(transactions[0].state == .awaitingAck)
        #expect(handler.motionQueueCount == 24)

        // Process through the queue
        for txn in transactions {
            handler.processAcknowledgment(transactionID: txn.id)
            handler.processResponse(transactionID: txn.id, response: "OK")
        }

        #expect(handler.motionQueueCount == 0)
        #expect(transactions.allSatisfy { $0.state == .completed })
    }

    @Test("Rapid submit and complete cycle")
    func testRapidCycle() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        for i in 0..<100 {
            let txn = handler.submit(RobotCommand("query\(i)", commandType: .query))
            handler.processAcknowledgment(transactionID: txn.id)
            handler.processResponse(transactionID: txn.id, response: "OK\(i)")

            #expect(txn.state == .completed)
            #expect(txn.response == "OK\(i)")
        }

        #expect(pipe.sentCommands.count == 100)
    }

    @Test("Mixed category concurrent operations")
    func testMixedCategories() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        // Submit mixed categories
        let motion1 = handler.submit(RobotCommand("home", commandType: .motion))
        let query1 = handler.submit(RobotCommand("status", commandType: .query))
        let query2 = handler.submit(RobotCommand("pose", commandType: .query))
        let settable1 = handler.submit(RobotCommand("setPoint", commandType: .settable))
        let motion2 = handler.submit(RobotCommand("moveto", commandType: .motion))

        // Motion blocks motion, queries run parallel, settable is independent
        #expect(motion1.state == .awaitingAck)
        #expect(motion2.state == .queued)
        #expect(query1.state == .awaitingAck)
        #expect(query2.state == .awaitingAck)
        #expect(settable1.state == .awaitingAck)

        // Complete motion1, motion2 should start
        handler.processAcknowledgment(transactionID: motion1.id)
        handler.processResponse(transactionID: motion1.id)

        #expect(motion1.state == .completed)
        #expect(motion2.state == .awaitingAck)
    }

    @Test("Cancel all clears everything")
    func testCancelAll() {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let motion1 = handler.submit(RobotCommand("home", commandType: .motion))
        let motion2 = handler.submit(RobotCommand("moveto", commandType: .motion))
        let query1 = handler.submit(RobotCommand("status", commandType: .query))
        let settable1 = handler.submit(RobotCommand("setPoint", commandType: .settable))

        handler.cancelAll()

        #expect(motion1.state == .failed)
        #expect(motion2.state == .failed)
        #expect(query1.state == .failed)
        #expect(settable1.state == .failed)
        #expect(handler.motionQueueCount == 0)
        #expect(handler.activeQueryCount == 0)
    }
}

// MARK: - Publisher Tests

@Suite("TransactionHandler Publisher Tests")
struct PublisherTests {

    @Test("Device state publisher emits changes")
    func testDeviceStatePublisher() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .disconnected)

        var receivedStates: [DeviceState] = []
        var cancellables = Set<AnyCancellable>()

        handler.deviceStatePublisher
            .sink { state in
                receivedStates.append(state)
            }
            .store(in: &cancellables)

        handler.updateDeviceState(.idle)
        handler.updateDeviceState(.busy)
        handler.updateDeviceState(.idle)

        #expect(receivedStates.contains(.idle))
        #expect(receivedStates.contains(.busy))
    }

    @Test("Transaction state publisher emits changes")
    func testTransactionStatePublisher() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .query))

        var receivedStates: [TransactionState] = []
        var cancellables = Set<AnyCancellable>()

        txn.statePublisher
            .sink { state in
                receivedStates.append(state)
            }
            .store(in: &cancellables)

        handler.processAcknowledgment(transactionID: txn.id)
        handler.processResponse(transactionID: txn.id)

        #expect(receivedStates.contains(.executing))
        #expect(receivedStates.contains(.completed))
    }

    @Test("Transaction result publisher emits results")
    func testTransactionResultPublisher() async throws {
        let handler = TransactionHandler<RobotCommand>(resourceID: "test-robot", initialState: .idle)
        let pipe = MockTransactionPipe()
        handler.attachPipe(pipe)

        let txn = handler.submit(RobotCommand("status", commandType: .query))

        var receivedResults: [TransactionResult] = []
        var cancellables = Set<AnyCancellable>()

        txn.resultPublisher
            .sink { result in
                receivedResults.append(result)
            }
            .store(in: &cancellables)

        handler.processAcknowledgment(transactionID: txn.id)
        handler.processResponse(transactionID: txn.id, response: "RUNNING")

        #expect(receivedResults.count >= 2)

        // Check for acknowledged result
        let hasAck = receivedResults.contains { result in
            if case .acknowledged = result { return true }
            return false
        }
        #expect(hasAck)

        // Check for completed result
        let hasCompleted = receivedResults.contains { result in
            if case .completed(_, let response) = result {
                return response == "RUNNING"
            }
            return false
        }
        #expect(hasCompleted)
    }
}
